name: "Release"

on:
  push:
    tags: ["v*"]
    branches: ["develop"]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  MISE_EXPERIMENTAL: true

jobs:
  binary:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2

      - name: Build the executable
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          VERSION: ${{ github.ref_name }}
        run: go build -ldflags="-s -w -X main.version=$VERSION" -o ghstats-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Rename the executable
        if: ${{ matrix.goos == 'windows' }}
        run: mv ghstats-${{ matrix.goos }}-${{ matrix.goarch }} ghstats-${{ matrix.goos }}-${{ matrix.goarch }}.exe

      - name: Install UPX
        run: sudo apt-get update && sudo apt-get install -y upx

      - name: Package the executable
        if: ${{ ! (matrix.goos == 'windows' && matrix.goarch == 'arm64') }}
        run: upx --best --lzma --force-macos ghstats*

      - name: Release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          preserve_order: true
          files: |
            ghstats-${{ matrix.goos }}-${{ matrix.goarch }}
            ghstats-${{ matrix.goos }}-${{ matrix.goarch }}.exe
